services:
  postgres:
    container_name: 'gui-test-2'
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pulgadata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD='123123'

volumes:
  pulgadata:
    external: true