services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - guidata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sequelize

volumes:
  guidata:
    external: true