POST http://localhost:3000/users
Accept: application/json
Content-Type: application/json

{
  "name": "Eduardo",
  "email": "eduardo@galvao.com",
  "password": "password"
}

###

GET http://localhost:3000/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJndWlsaGVybWVAc291emEuY29tIiwiaWF0IjoxNzM5ODc5MDI4LCJleHAiOjE3Mzk5NjU0Mjh9.LzxRskmaf-Favzvkxp1bgyrV6S-YKiNnP730PeXEAIQ
